### PR TITLE
RoseTree example: Use a more general map function

### PR DESCRIPTION
**Pull request by nomeata**
The `map_In` that I use here has (I believe) the most general type that
still allows the reasoning required to make the nested examples go
through. Note that it does not depend on the actual size function, and
would work equally well in a proof with a well-founded relation instead
of a measure.

### CODE REVIEW

**Comment by nomeata** [comment]
I believe `map_In` is a slightly better idiom and would be happy to see that in the official repository, but this is obviously not a big deal if you have reasons to prefer the original variant.

**Comment by nomeata** [comment]
I believe `map_In` is a slightly better idiom and would be happy to see that in the official repository, but this is obviously not a big deal if you have reasons to prefer the original variant.

**Comment by mattam82** [comment]
Sounds like a good idea indeed! I wish there was a way to justify it’s the canonical most general type for the functional but I don’t have an argument for it. I’ll try to see why funelim fails here and merge it.

**Comment by nomeata** [comment]
> I wish there was a way to justify it’s the canonical most general type for the functional but I don’t have an argument for it.

I expect it follows from parametricity somehow.

**Comment by mattam82** [comment]
Parametricity does not give a complete specification of map, quite far from it, as the same free theorem, in unary version something like:
```coq
forall A B (P : A -> Type) (Q : B -> Type) (f : A -> B),
  (forall x : A, P x -> Q x) -> forall l : list A, Forall P l -> Forall Q (map f l)
```

would hold as well for rev_map. I.e. the spec forgets the order in which the function is applied. But it's the commonly used spec indeed.

**Comment by mattam82** [comment]
The funelim problem is a bug, it tries to generalize the goal by all the arguments of map somehow, including the types A and B, making the generalized equality untypable. I can only find a partial fix for now, so merging this.

**Comment by nomeata** [comment]
> Parametricity does not give a complete specification of map, quite far from it

But it does imply that the argument `f` is only ever applied to members of `l`, isn’t it? The order is irrelevant for determining termination of a recursion that is nested through `map` (or `rev_map`).

**Comment by mattam82** [comment]
Absolutely, for recursion I think that's the most general you can get. The same would hold for folds I believe.

**Pull request merged**
