### PR TITLE
Avoid relying on `Export` bugs

### PR DESCRIPTION
**Pull request by maximedenes**
See https://github.com/coq/coq/issues/10474 and
https://github.com/coq/coq/issues/10480

### CODE REVIEW

**Comment by maximedenes** [comment]
This was a bit tricky because it interacts with https://github.com/coq/coq/issues/10556 and with the strange error handling logic in https://github.com/mattam82/Coq-Equations/blob/7cf2c9c76fbae8a5333154a7c6ef637e5ca7b087/src/principles.ml#L1322-L1330

**Comment by maximedenes** [comment]
@mattam82 I don't understand the CI failure. Is it what is holding this PR?

**Comment by mattam82** [comment]
Strange failure indeed, it looks unrelated to your change. Not sure I’ll have time to check what’s happening before my vacations sadly.

**Comment by maximedenes** [comment]
@mattam82 the master bulid fails with the same error, so it is unrelated. Can you merge this to avoid blocking the upstream PR?

**Comment by mattam82** [comment]
Sure!

**Comment by maximedenes** [comment]
Thanks a lot!

**Pull request merged**
