### PR TITLE
Fix for coq/coq#1033.

### PR DESCRIPTION
**Pull request by SkySkimmer**
By the way there seems to be an evar leak in eqdec.ml derive_eq_dec (sigma is used after evdref) which I'll let you fix independently so it can be fixed in master.

### CODE REVIEW

**Comment by mattam82** [comment]
Hmm you're right there's unneeded duplication there. I'll push the evar leak fix to master.

**Comment by mattam82** [comment]
So I'll just merge this when coq#1033 lands, right?

**Comment by mattam82** [comment]
This github conflict resolution thingy didn't seem to work

**Comment by SkySkimmer** [comment]
Manual fix done.
>I'll just merge this when coq/coq#1033 lands, right?

yes

**Pull request merged**
