### PR TITLE
[coq] Adapt to coq/coq#11836

### PR DESCRIPTION
**Pull request by ejgallego**
This commit is a bit large due to extensive update of obligations in hook callbacks, maybe code could be refactored a bit? I'm open to suggestions.

### CODE REVIEW

**Comment by mattam82** [comment]
I don’t see how to refactor yet. The chain of derived notions from a definition all use obligations. However, when a hook is called it should mean that the associated definition is finished, so what remains in the program state passed to hooks?

**Comment by ejgallego** [comment]
> I don’t see how to refactor yet.

An idea would be to have a small DSL that specifies what the continuations would be, but the current solution is OK IMHO.

> The chain of derived notions from a definition all use obligations. However, when a hook is called it should mean that the associated definition is finished, so what remains in the program state passed to hooks?

The hook can open new obligations, this is why the state is needed, mainly for the inner calls to `add_definition`; you need to pass it around so previous adds are preserved. IMHO the current way is OK.

Note that an interesting effect on how things are done today [if you look at coq/coq#11836 , declare.ml] is that the hook is called with the solved obligations still in the program map, this is the way it worked before, imperatively, not sure this is what we want tho.

**Comment by SkySkimmer** [comment]
Please merge now.

**Comment by ejgallego** [comment]
Ping @ppedrot @mattam82 [I know both of you are away but Pierre-Marie is sometimes around ;)]

**Comment by SkySkimmer** [comment]
@cmangin can merge here too IIUC

**Pull request merged**
