### PR TITLE
Fix incorrect #[universes(template)] annotation

### PR DESCRIPTION
**Pull request by mattam82**
Allowing coq/coq#9918 to pass

### CODE REVIEW

**Comment by vbgl** [comment]
This should be also applied to the 8.10 branch. Thanks.

**Comment by mattam82** [comment]
@vbgl Done

**Comment by vbgl** [comment]
Thanks. It seems that commit 54751604cbe96bf73a0e1708dc5ed99ecb7fee01 should also be applied to the 8.10 branch.

**Comment by mattam82** [comment]
@vbgl I backported it to all branches.

**Pull request merged**
