### PR TITLE
HoTT Logic

### PR DESCRIPTION
**Pull request by mattam82**
This provides an instance of Equations working with the HoTT library (reusing the definition of equality defined there). Care has been taken that simplification of dependent pattern-matching does not generate unnecessary universes (but programs with obligations get many spurious ones, that's a problem in Coq). Well-founded fixpoints (in Type) generate a few necessary universes.

This changes the building setup, requiring a ./configure.sh HoTT|coq (default) command to generate the proper makefile (only the theories/ that are compiled change).

### CODE REVIEW

**Comment by ppedrot** [comment]
@mattam82 this needs a rebase

**Comment by ppedrot** [comment]
@mattam82 should this be merged before the branch of 8.11? coq/coq#9786 is waiting on this and it looks like an important change.

**Comment by mattam82** [comment]
Yep, I'll do that.

**Comment by mattam82** [comment]
Let's see. The previous error in the test-suite I couldn't reproduce locally... Rebased on equations' master as well.

**Comment by mattam82** [comment]
Not only Coq changed but HoTT-coq renamed `relation` to `Relation`, most strangely to me. Thankfully the code is immune to these choices once we use `Register Constant` :)

**Pull request merged**
