### PR TITLE
Adapt to https://github.com/coq/coq/pull/12523

### PR DESCRIPTION
**Pull request by ejgallego**
Please merge.

### CODE REVIEW

**Comment by Zimmi48** [comment]
Travis is pinned to 8.12+beta1. Changing it to use `8.12.dev` should make the build go through.

**Comment by ejgallego** [comment]
> Travis is pinned to 8.12+beta1. Changing it to use `8.12.dev` should make the build go through.

Done, thanks.

**Comment by Zimmi48** [comment]
@ppedrot Would you mind merging this?
@mattam82 You will have to do a new release for 8.12.0 compatibility.
@ejgallego We should switch from the pinned commit in your fork back to the 8.12 branch of this repo once this PR is merged.

**Comment by mattam82** [comment]
Ok, noted!

**Pull request merged**
