### PR TITLE
[coq] Adapt to coq/coq#6413.

### PR DESCRIPTION
**Pull request by ejgallego**
After going too far trying to functionalize the code, I backtrack and do the simple thing.

### CODE REVIEW

**Comment by mattam82** [comment]
LGTM

**Comment by Zimmi48** [comment]
The PR in Coq was merged.

**Comment by Zimmi48** [comment]
I'm sorry I sent a false alarm :(

**Comment by ejgallego** [comment]
Well, coq/coq#6413 is ready to merge thou if that is gonna solve the mess.

**Comment by ejgallego** [comment]
[It worked in my Travis]

**Comment by Zimmi48** [comment]
Sorry :(

**Comment by Zimmi48** [comment]
This time the corresponding PR was merged for real.

**Pull request merged**
