### PR TITLE
[coq] Overlay for coq/coq#9567 "unify hooks"

### PR DESCRIPTION
**Pull request by ejgallego**
We fix a couple of fatal warnings too.

### CODE REVIEW

**Comment by maximedenes** [comment]
Are the dune changes intended?

**Comment by ejgallego** [comment]
Yes they revert a PR we merged by error.

**Comment by maximedenes** [comment]
> Yes they revert a PR we merged by error.

This seems like very bad practice to me, but ok...

**Comment by maximedenes** [comment]
The Coq PR has been merged, please merge this. Thanks!

**Comment by ejgallego** [comment]
> This seems like very bad practice to me, but ok...

I guess we are not perfect :sweat_smile: :sweat_smile: specially when dealing with experimental stuff.

**Comment by maximedenes** [comment]
> I guess we are not perfect   specially when dealing with experimental stuff.

Sure, I meant you could have submitted the fix separately.

**Pull request merged**
